server:
  port: 8088
  session-timeout: 1800
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uc_main_demo?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    show-sql: true
  redis:
    shiro:
      host: localhost
      port: 6379
      password: redis
      # 连接超时时间（毫秒）
      timeout: 10000
 
logging:
  level:
    com.ucomponent : debug